services:
  frontend:
    volumes:
      - /app/node_modules
      - ./frontend:/app
  
  question:
    command: npm run dev
    ports:
      - 8081:8081
    volumes:
      - /app/node_modules
      - ./services/question:/app

  question-db:
    ports:
      - 27017:27017

  user:
    command: npm run dev
    ports:
      - 8082:8082
    volumes:
      - /app/node_modules
      - ./services/user:/app
  
  user-db:
    ports:
      - 27018:27017