export enum Queues {
    MATCH_REQUEST_UPDATED = 'MATCH_REQUEST_UPDATED',
    MATCH_FOUND = 'MATCH_FOUND',
    QUESTION_FOUND = 'QUESTION_FOUND',
    COLLAB_CREATED = 'COLLAB_CREATED',
    MATCH_FAILED = 'MATCH_FAILED',
}
